name             'btrfs_snap'
maintainer       'James FitzGibbon'
maintainer_email 'james@nadt.net'
license          'All rights reserved'
description      'Installs btrfs-snap for Ubuntu and provides LWRPs to take snapshots'
version          '0.3.5'
supports         'ubuntu', '>= 12'
